name: NuGet Publish

on:
  push:
    branches:
      - master # Default release branch, may also be named 'master' or 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Publish package to NuGet
      run: dotnet nuget push *.nupkg --api-key oy2e54gywqsmgfgerf4qpsf3zee7vo7u5f2hykmq3ltjpq --source "https://api.nuget.org/v3/index.json" --skip-duplicate
